import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import "./globals.css";
import App from "./App";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Betcha",
  description: "Generated by create next app",
  icons: {
    icon: "/dropbox.ico",
    apple: "/apple-touch-icon.png", // Apple devices
    shortcut: "/shortcut-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}
